from typing import Protocol, runtime_checkable


@runtime_checkable
class KafkaProducer(Protocol):
    async def start(self) -> None: ...
    async def stop(self) -> None: ...
    async def send_response_add(self, response_id: str, task_id: str, user_id: str) -> None: ...
    async def send_response_delete(self, response_id: str, task_id: str) -> None: ...
