from typing import BinaryIO, Protocol, runtime_checkable
from uuid import UUID


@runtime_checkable
class MediaClient(Protocol):
    async def add_attached_file(self, file: BinaryIO, filename: str) -> UUID: ...
    async def get_attached_file(self, file_id: UUID) -> bytes: ...
    async def delete_attached_file(self, file_id: UUID) -> bool: ...
    async def close(self) -> None: ...
