from typing import List, Optional, Protocol, runtime_checkable
from uuid import UUID

from src.models.comment import Comment


@runtime_checkable
class CommentRepository(Protocol):
    async def add_comment(self, comment: Comment) -> Comment: ...
    async def get_comment(self, comment_id: UUID) -> Optional[Comment]: ...
    async def delete_comment(self, comment_id: UUID) -> bool: ...
    async def get_comments_for_response(self, response_id: UUID) -> List[Comment]: ...
