from typing import Any, Dict, List, Optional, Protocol, runtime_checkable
from uuid import UUID

from src.models.response import Response, ResponseStatus


@runtime_checkable
class ResponseRepository(Protocol):
    async def get_task_responses(self, task_id: UUID) -> List[Response]: ...
    async def get_response(self, response_id: UUID) -> Optional[Response]: ...
    async def add_response(self, response: Response) -> Response: ...
    async def change_response(self, response_id: UUID, update_data: Dict[str, Any]) -> Optional[Response]: ...
    async def delete_response(self, response_id: UUID) -> bool: ...
    async def change_response_status(self, response_id: UUID, status: ResponseStatus) -> Optional[Response]: ...
    async def append_to_attached_files(self, response_id: UUID, file_id: UUID) -> bool: ...
    async def remove_from_attached_files(self, response_id: UUID, file_id: UUID) -> bool: ...
